version: '3'

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - task-service

  task-service:
    build: ./task-service
    ports:
      - "3001:3001"

  sync-service:
    build: ./sync-service
    ports:
      - "3002:3002"

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"